<?php
/**
 * @package     phast/app
 * @subpackage  Modules/Product/Models/ValueObjects
 * @file        ProductId
 * @author      Generated by Phast Framework
 * @date        2025-07-05
 * @version     1.0.0
 * @description Value object for Product module
 */

declare(strict_types=1);

namespace Phast\App\Modules\Product\Models\ValueObjects;

class ProductId
{
    private string $value;

    public function __construct(string $value)
    {
        $this->validate($value);
        $this->value = $value;
    }

    public function getValue(): string
    {
        return $this->value;
    }

    public function equals(ProductId $other): bool
    {
        return $this->value === $other->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }

    public function toArray(): array
    {
        return [
            'value' => $this->value
        ];
    }

    private function validate(string $value): void
    {
        if (empty(trim($value))) {
            throw new \InvalidArgumentException('ProductId cannot be empty');
        }

        // TODO: Add specific validation rules for this value object
        // Example: email validation, phone number format, etc.
    }

    /**
     * Create from string
     */
    public static function fromString(string $value): self
    {
        return new self($value);
    }
}
