<?php
/**
 * @package     phast/app
 * @subpackage  Modules/Product
 * @file        routes
 * @author      Generated by Phast Framework
 * @date        2025-07-05
 * @version     1.0.0
 * @description Product module routes
 */

declare(strict_types=1);

// Note: $router is already available from the parent scope

$router->group(['prefix' => 'product'], function ($router) {
    // Public routes
    $router->get('/', 'Phast\App\Modules\Product\Controllers\ProductController@index')
        ->name('product.index');

    $router->get('/{id}', 'Phast\App\Modules\Product\Controllers\ProductController@show')
        ->name('product.show');

    // Protected routes
    $router->group([
        'middleware' => [\Phast\Core\Http\Middleware\AuthMiddleware::class]
    ], function ($router) {
        $router->post('/', 'Phast\App\Modules\Product\Controllers\ProductController@store')
            ->name('product.store');

        $router->put('/{id}', 'Phast\App\Modules\Product\Controllers\ProductController@update')
            ->name('product.update');

        $router->delete('/{id}', 'Phast\App\Modules\Product\Controllers\ProductController@destroy')
            ->name('product.destroy');
    });
});
