<?php
/**
 * @package     phast/app
 * @subpackage  Modules/Blog/Providers
 * @file        BlogServiceProvider
 * @author      Generated by Phast Framework
 * @date        2025-07-05
 * @version     1.0.0
 * @description Service provider for Blog module
 */

declare(strict_types=1);

namespace Phast\App\Modules\Blog\Providers;

use League\Container\ServiceProvider\AbstractServiceProvider;

class BlogServiceProvider extends AbstractServiceProvider
{
    protected $provides = [
        // Register services that this provider provides
    ];

    public function register(): void
    {
        // Register module services in the container
        
        // Example:
        // $this->container->add(SomeService::class)->addArgument(SomeDependency::class);
    }

    public function boot(): void
    {
        // Bootstrap module (called after all providers are registered)
        
        // Example: Register event listeners, setup module configuration, etc.
    }
}
