<?php
/**
 * @package     phast/app
 * @subpackage  Modules/Blog
 * @file        routes
 * @author      Generated by Phast Framework
 * @date        2025-07-05
 * @version     1.0.0
 * @description Blog module routes
 */

declare(strict_types=1);

// Note: $router is already available from the parent scope

$router->group(['prefix' => 'blog'], function ($router) {
    // Public routes
    $router->get('/', function () {
        return response()->json([
            'message' => 'Welcome to Blog module',
            'module' => 'Blog',
            'endpoints' => [
                'GET /' => 'This endpoint',
                // Add more endpoints here
            ]
        ]);
    })->name('blog.index');

    // Protected routes
    $router->group([
        'middleware' => [\Phast\Core\Http\Middleware\AuthMiddleware::class]
    ], function ($router) {
        // Add authenticated routes here
    });
});
